from pathlib import Path

from app.engines.base import GenerationEngine
from app.schemas import EngineInfo, EnginePurpose, GenerationMode, OutputFormat


class MockEngine(GenerationEngine):
    info = EngineInfo(
        name="mock",
        display_name="Built-in Test Mesh",
        description="Creates a simple OBJ mesh so the API can be tested without a GPU model installed.",
        supports=[GenerationMode.single, GenerationMode.multi],
        output_formats=[OutputFormat.obj],
        purpose=EnginePurpose.test,
        quality_notes="Not a real image-to-3D model. Use only for API/UI testing.",
        storage_notes="Tiny generated files; safe for development.",
    )

    def generate(
        self,
        *,
        job_id: str,
        mode: GenerationMode,
        input_paths: list[Path],
        output_path: Path,
        output_format: OutputFormat,
    ) -> dict:
        if output_format != OutputFormat.obj:
            raise ValueError("mock engine only supports OBJ output")

        scale = max(1, len(input_paths))
        output_path.write_text(
            "\n".join(
                [
                    f"# Generated by Open 3D Generator API mock engine for job {job_id}",
                    f"# mode={mode.value} inputs={len(input_paths)}",
                    "o generated_asset",
                    f"v {-1 * scale} {-1 * scale} 0",
                    f"v {1 * scale} {-1 * scale} 0",
                    f"v {1 * scale} {1 * scale} 0",
                    f"v {-1 * scale} {1 * scale} 0",
                    f"v 0 0 {1.5 * scale}",
                    "f 1 2 5",
                    "f 2 3 5",
                    "f 3 4 5",
                    "f 4 1 5",
                    "f 1 4 3 2",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        return {"engine": self.info.name, "vertices": 5, "faces": 5}
